export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const DELETE_COMMENT_OPTIMISTIC = "DELETE_COMMENT_OPTIMISTIC";
